### ISSUE TITLE
pipx run validate-pyproject --help

### ISSUE THREAD

**Issue by cclauss** [abravalheri/validate-pyproject#63]
Unfortunately, the following command fails:
% `pipx run validate-pyproject --help`
```
Traceback (most recent call last):
  File "/Users/cclauss/.local/pipx/.cache/780fbd20a9477c3/lib/python3.10/site-packages/validate_pyproject/cli.py", line 39, in <module>
    from tomli import TOMLDecodeError, loads
ModuleNotFoundError: No module named 'tomli'
```

**Comment by cclauss** [comment]
`pipx install validate-pyproject && pipx inject validate-pyproject tomli ` # works!

**Comment by abravalheri** [comment]
Hi @cclauss, `validate-pyproject` comes in 2 "flavours":

- `validate-pyproject[all]` includes all the dependencies for standalone usage
- `validate-pyproject` that targets library developers and does not include any provision for parsing TOML as they might select different libraries.

(This happens because in Python it is not very easy to use optional "extras" to remove dependencies. On the other hand it is very trivial to use "extras" to add dependencies).

I believe you can run `pipx run 'validate-pyproject[all]' --help`

**Comment by cclauss** [comment]
Yes.  That worked perfectly.  This was a case where I did not RFTM.
